package ai

// Request represents a request sent to an AI provider.
type Request struct {
	Input string
}

// Response represents a response generated by an AI provider.
type Response struct {
	Content string
}
